//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodTable
    {
        public FoodTable()
        {
            this.Tickets = new HashSet<Ticket>();
            this.UsersFoodTables = new HashSet<UsersFoodTable>();
        }
    
        public int ID { get; set; }
        public int Status { get; set; }
        public string Info { get; set; }
    
        public virtual ICollection<Ticket> Tickets { get; set; }
        public virtual ICollection<UsersFoodTable> UsersFoodTables { get; set; }
    }
}
