//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantApplicationEntities : DbContext
    {
        public RestaurantApplicationEntities()
            : base("name=RestaurantApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FoodTable> FoodTables { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<TicketsMenuItem> TicketsMenuItems { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersFoodTable> UsersFoodTables { get; set; }
        public virtual DbSet<UsersRole> UsersRoles { get; set; }
        public virtual DbSet<v_TicketsMenuItems> v_TicketsMenuItems { get; set; }
        public virtual DbSet<v_UsersRoles> v_UsersRoles { get; set; }
    }
}
