//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.TicketsMenuItems = new HashSet<TicketsMenuItem>();
        }
    
        public int ID { get; set; }
        public int TableID { get; set; }
        public System.DateTime TimePlaced { get; set; }
        public Nullable<System.DateTime> TimeCompleted { get; set; }
        public bool TicketClosed { get; set; }
    
        public virtual FoodTable FoodTable { get; set; }
        public virtual ICollection<TicketsMenuItem> TicketsMenuItems { get; set; }
    }
}
