//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketsMenuItem
    {
        public int TicketID { get; set; }
        public int MenuItemID { get; set; }
        public decimal PricePaid { get; set; }
        public bool Returned { get; set; }
        public string ReturnReason { get; set; }
        public bool ManagerComped { get; set; }
        public Nullable<int> CompedByUserID { get; set; }
        public int ID { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
