//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.TicketsMenuItems = new HashSet<TicketsMenuItem>();
            this.UsersFoodTables = new HashSet<UsersFoodTable>();
            this.UsersRoles = new HashSet<UsersRole>();
            this.UserTimeClockEntries = new HashSet<UserTimeClockEntry>();
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<TicketsMenuItem> TicketsMenuItems { get; set; }
        public virtual ICollection<UsersFoodTable> UsersFoodTables { get; set; }
        public virtual ICollection<UsersRole> UsersRoles { get; set; }
        public virtual ICollection<UserTimeClockEntry> UserTimeClockEntries { get; set; }
    }
}
