//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_TicketsMenuItems
    {
        public int TicketID { get; set; }
        public int TableID { get; set; }
        public System.DateTime TimePlaced { get; set; }
        public Nullable<System.DateTime> TimeCompleted { get; set; }
        public string Title { get; set; }
        public decimal PricePaid { get; set; }
        public bool Returned { get; set; }
        public string ReturnReason { get; set; }
        public bool ManagerComped { get; set; }
        public Nullable<int> CompedByUserID { get; set; }
    }
}
